FROM ros:humble-ros-base-jammy

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        python3-colcon-common-extensions \
        python3-pip \
        ros-humble-diagnostic-msgs \
        ros-humble-example-interfaces \
        ros-humble-std-srvs \
        ros-humble-tf2-ros \
    && rm -rf /var/lib/apt/lists/*

COPY . /opt/fraeno
RUN python3 -m pip install /opt/fraeno

WORKDIR /work
