FROM ros@sha256:2a7ca548c7f0f87bc6393ee161dea3283e1c6fa280916f8944b1afadde2d26ec

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        python3-colcon-common-extensions \
        python3-pip \
        ros-humble-diagnostic-msgs \
        ros-humble-std-srvs \
        ros-humble-tf2-ros \
    && rm -rf /var/lib/apt/lists/*

COPY . /opt/fraeno
RUN python3 -m pip install /opt/fraeno

WORKDIR /work
